---
development:
  dialect: "mysql"
  database: "teste_db"
  user: "usuario"
  password: "c9dfa0776bb7e16"
  host: "172.10.0.1"
  port: "3307"

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/teste_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/teste_production?sslmode=disable"}}
